[package]
name        = "sg-swap-pair-stable"
version     = { workspace = true }
authors     = ["Cosmorama <cosmorama@proton.me>"]
edition     = { workspace = true }
description = "Stargaze swap stableswap pair contract implementation"
license     = { workspace = true }

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library    = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw2             = { workspace = true }
cw20            = { workspace = true }
cw20-base       = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils        = { workspace = true }
itertools       = { workspace = true }
sg-swap         = { workspace = true }

[dev-dependencies]
anyhow          = { workspace = true }
cw-multi-test   = { workspace = true }
derivative      = { workspace = true }
proptest        = { workspace = true }
sg-swap-factory = { workspace = true }
sg-swap-stake   = { workspace = true }
